//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_Page.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthorizeCode
    {
        public AuthorizeCode()
        {
        }

        public AuthorizeCode(int id, string newCode, DateTime createdDate, DateTime endDate)
        {
            codeId = id;
            code = newCode;
            createDate = createdDate;
            expiredDate = endDate;
        }

        public int codeId { get; set; }
        public string code { get; set; }
        public System.DateTime createDate { get; set; }
        public System.DateTime expiredDate { get; set; }
    }
}
